name: Deploy Preview to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHATAPP_5EFD4 }}'
          projectId: 'chatapp-5efd4'