name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main    # << IMPORTANT: Deploy only when push happens to MAIN branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHAT_APP_FIREBASE }}"
          channelId: live
          projectId: 'chatapp-5efd4'
